all:
# 	g++ -std=c++11 suffix_tree.cpp -o st
# 	g++ -std=c++11 brute_force_pattern_matching.cpp -o bfpm
# 	g++ -std=c++11 Algoritmsuffixcode.cpp -o st2
# 	g++ -std=c++11 Algoritmsuffixcode.cpp -o st
# 	g++ -std=c++11 all_agorithms.cpp -o all
	g++ -std=c++11 size_vs_text.cpp -o size_text